### PR TITLE
Sanitization on forms and any user input

### LINKED ISSUE #90: Server-side validation/sanitization on forms and any user input.
- Have validations for Post requests coming from forms

### PR DESCRIPTION
**Pull request by gleal42**
- Add validator to form user input (dto and file validators)
- Sanitize to user profile form input
- Added JWT guard to leaderboard and updated frontend
- Removed user controller that was not being used
- Fixed small frontend bug related to uploaded images when they are invalid

### CODE REVIEW

**Comment by ncameiri42** [comment]
On 1st Login (enable it to true on DB):
image

image

For Profile settings is ok!

**Comment by gleal42** [comment]
E era indiferente que username escolhiamos?

**Comment by ncameiri42** [comment]
É só adicionar o token no UserValidation.vue linha 166

**Review by ncameiri42 — APPROVED** [review]
LGTM!

**Pull request merged**
